language: node_js
script: npm test
node_js:
- node
- io.js
- '0.12'
notifications:
  email: false
deploy:
  provider: npm
  email: npm@eli-white.com
  api_key:
    secure: 5QxG5ZjDCkMB384GEB/vO4pGKd5VgHJLRQDrsWIxqhzNkPE4Nqm+6gQe1N9o8V0DVd4Rfqg1jRBdWdcqpTOzTJc06XevTcMC7gE6LSbZAZUuu/2DwHHCRBCpdy7eTTRqLxwxXfrrJnXXf6AYw9yVLtfCOYPPNWNVARbKdc0QqEW1Wq+hWqViT26b54AxEh8JBMemVL3Z1EhK3C+A19wkGZZB8lNTFogtCMmdQNEfsZQZM/MNl0hAfAGSBTYAKh7lgmodAXW1lzRkccSDJOczzLdF37kGrXx3sTqiDjo0w6NZoUzz6wkZXM4oO0c2zGYvy66thVQyiucQZFXCarvXbo7Z2ee4tckeIeikJ1jVE1JJAf+uDcjCGUS9iOT6TxVAAtugrKNyahjHmpGBhxXW7Ed6fJnx4+y0ASA74B4wmMEZNrKOm2rnmjDf+nuwQjMLOEa1Asv2fmaLDQ6ihDtTvUdycTJaUVxKMcUahuNZvTYCcJjFZ1KmE//su1XYnmFH7ahSFhA1jRGAGLTJUbjXkOCjxksF5HbtZOqrjHo4hgtmz86vwOLdiDFMgB2zlukd7FPWz5plhc7y/xUmkSt+LVA5Ch/GRTRCockpPZS3xa0DsSzVNxYamvm7qoNmvudyrcJPVq7ocOOTrv953Nxx+JpIz3rEhREjutfIK9nkyAw=
  on:
    tags: true
    repo: thea-diffing/thea-test-uploader
    node: node
